name: 1.0.0$(Rev:.r) #Build number

#Build variables
variables:
  App.Home: $(Build.SourcesDirectory)/
  App.Name: hgproxy

trigger:
  - master

pool:
  vmImage: "HealthGateway"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "11.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build
    displayName: "npm install and build"
